export const APP_LINKS = {
  internal: {
    home: "/",
    healthTwin: "/health-twin",
    avatarPlaybackTest: "/avatar-playback-test",
    howItWorks: "/how-it-works",
    hospitalValue: "/hospital-value",
    whyVeeVee: "/features",
    technology: "/technology",
    simulator: "/simulator",
    testimonials: "/testimonials",
    caregivers: "/caregivers",
    medicare: "/medicare-guidance",
    hospitalToHome: "/hospital-to-home",
    contact: "/contact",
    terms: "/terms",
    swcaBrief: "/briefs/swca-4821.html",
    swcaRewards: "/swca/rewards",
    swcaTeaserAlias: "/swca/teaser",
    swcaIntake: "/swca/intake",
    swcaWheel: "/swca/wheel",
    swcaFunnel: "/swca/funnel",
    swcaAdmin: "/swca/admin",
  },
  cta: {
    getStarted: "/",
    checkBenefits: "/",
    login: "https://veevee.io",
  },
  external: {
    authenticatedConsole: "https://veevee.io",
    investors: "https://investveevee.com",
  },
} as const;
